// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcSP2eAMEzSg5INmX0xWu3BXCbtbBW1Yw',
    appId: '1:899334954651:android:79c82a1177a900b626703e',
    messagingSenderId: '899334954651',
    projectId: 'buddy-da655',
    storageBucket: 'buddy-da655.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC47UsU-5hMcdz4ToJHLNoUENxz3QRTntE',
    appId: '1:899334954651:ios:bce09487248b100426703e',
    messagingSenderId: '899334954651',
    projectId: 'buddy-da655',
    storageBucket: 'buddy-da655.appspot.com',
    androidClientId: '899334954651-9a8ll5pu2oocnlvg0462plb5skskk2bo.apps.googleusercontent.com',
    iosClientId: '899334954651-61qeuvpen5luv2bvm8hoeac681r6gdn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTi3_hBWtRlQgE6vLkR-de7rWJGE_8-Sk',
    appId: '1:899334954651:web:4076012f0625788c26703e',
    messagingSenderId: '899334954651',
    projectId: 'buddy-da655',
    authDomain: 'buddy-da655.firebaseapp.com',
    storageBucket: 'buddy-da655.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTi3_hBWtRlQgE6vLkR-de7rWJGE_8-Sk',
    appId: '1:899334954651:web:b099b89cd4d1baa126703e',
    messagingSenderId: '899334954651',
    projectId: 'buddy-da655',
    authDomain: 'buddy-da655.firebaseapp.com',
    storageBucket: 'buddy-da655.appspot.com',
  );

}